
package example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PeopleController", targetNamespace = "http://Server.example", wsdlLocation = "file:/C:/Users/Dell/Documents/TPO_project10/src/example/client/PeopleController.wsdl")
public class PeopleController_Service
    extends Service
{

    private final static URL PEOPLECONTROLLER_WSDL_LOCATION;
    private final static WebServiceException PEOPLECONTROLLER_EXCEPTION;
    private final static QName PEOPLECONTROLLER_QNAME = new QName("http://Server.example", "PeopleController");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Dell/Documents/TPO_project10/src/example/client/PeopleController.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEOPLECONTROLLER_WSDL_LOCATION = url;
        PEOPLECONTROLLER_EXCEPTION = e;
    }

    public PeopleController_Service() {
        super(__getWsdlLocation(), PEOPLECONTROLLER_QNAME);
    }

    public PeopleController_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEOPLECONTROLLER_QNAME, features);
    }

    public PeopleController_Service(URL wsdlLocation) {
        super(wsdlLocation, PEOPLECONTROLLER_QNAME);
    }

    public PeopleController_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEOPLECONTROLLER_QNAME, features);
    }

    public PeopleController_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PeopleController_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PeopleController
     */
    @WebEndpoint(name = "PeopleController")
    public PeopleController getPeopleController() {
        return super.getPort(new QName("http://Server.example", "PeopleController"), PeopleController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeopleController
     */
    @WebEndpoint(name = "PeopleController")
    public PeopleController getPeopleController(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server.example", "PeopleController"), PeopleController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEOPLECONTROLLER_EXCEPTION!= null) {
            throw PEOPLECONTROLLER_EXCEPTION;
        }
        return PEOPLECONTROLLER_WSDL_LOCATION;
    }

}
